//
//  ResultsPageViewController.h
//  endthedebate
//
//  Created by Khang Le on 1/5/14.
//  Copyright (c) 2014 Khang Le. All rights reserved.
//

#import <UIKit/UIKit.h>

#import "Question.h"

/**
 A UIViewController that presents the results in the form of a UIScrollView of multiple
 different types of graphs. These graphs are generated by the ResultsViewController (pie graph),
 the BarResultController (bar graph), and MapResultController (map graph). These controllers are held
 in a NSMutableArray that is generated in the viewDidLoad function.
 */
@interface ResultsPageViewController : UIViewController

/**
 Initialize the results page with the given answers and the question that corresponds to those answers.
 @param answers The answers for the given question that will be loaded into the graphs
 @param question The question that will be loaded into the graphs
 */
- (id)initWithArray:(NSMutableArray*)answers forQuestion:(Question*)question;

@end
